### ISSUE TITLE
Example with an external module like react-native-maps, react-native-firebase or something like this

### ISSUE THREAD

**Issue by suupham2506** [votrai123/integrate-multiple-react-native#3]
**Is your feature request related to a problem? Please describe.**
Currently, I am not able to add the external module to the app by following your outstanding article on medium.

**Describe the solution you'd like**
I would like to have an example that we could use external module for the mini app. Much appreciated if you could publish another article in detail for the way how to implement an external module as my suggestion.

Many thanks, @votrai123

**Comment by votrai123** [comment]
That's not a bad idea. I think it's not a significant issue for my repository and Medium posts because I cannot anticipate what libraries you want to install and how they might affect the native code. 

For [react-native-maps](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md) perhaps you missed its installation instructions. Nevertheless, I can assist you with an example in the [example-install-lib](https://github.com/votrai123/integrate-multiple-react-native/tree/example-install-lib) branch; please follow it. 
#1
